// Automatically generated by scripts/apply-prefs.sh
/* Performance and WebRender optimizations — tuned for high-workload web apps */
// Increased maximum persistent connections per server
user_pref("network.http.max-persistent-connections-per-server", 8);

// Force WebRender on (may still depend on environment/drivers)
user_pref("gfx.webrender.enabled", true);
user_pref("gfx.webrender.all", true);
user_pref("gfx.webrender.force-enabled", true);

// Layers / acceleration
user_pref("layers.acceleration.enabled", true);
user_pref("layers.acceleration.force-enabled", true);

// Adaptive content process count
user_pref("dom.ipc.processCount", 2);

// Disable disk cache to reduce I/O in ephemeral environments
user_pref("browser.cache.disk.enable", false);

// Encourage using memory cache (useful when disk cache is disabled)
user_pref("browser.cache.memory.enable", true);
user_pref("browser.cache.memory.capacity", 1048576);

// WebGL / VA-API helpers
user_pref("webgl.enable-webgl2", true);
user_pref("webgl.force-enabled", true);
user_pref("media.hardware-video-decoding.enabled", true);

// Reduce disk I/O caused by sessionstore
user_pref("browser.sessionstore.interval", 300000);
user_pref("browser.sessionstore.max_tabs_undo", 0);

// Telemetry / background services we don't need for performance testing
user_pref("toolkit.telemetry.unified", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("browser.discovery.enabled", false);

